baseURL = "https://ali.sattari.me/"
languageCode = "en-us"
title = "Ali's Blog"
theme = "ink"

copyright = "All contents under <a href=\"https://www.gnu.org/licenses/fdl-1.3.html\">GNU FDL</a>"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[pagination]
pagerSize = 10

[permalinks]
  posts = "/posts/:year/:slug"

[params]
	subtitle = "Mostly about technology, sometimes about other stuff!"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]

	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

# Nav.
[[menu.main]]
name = "About"
url = "/about"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/ali-sattari"

[[params.social]]
name = "Hardcover"
icon = "book-open"
url = "https://hardcover.app/@ali.sattari"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/alisattari/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
  tag = "tags"
  category = "categories"
